Repository codestates-seb/seb40_main_013, pull requests merged in 2022-12, with the labels that each got.

#168 [Client] 무한스크롤 구현 중
  client/package-lock.json
  client/package.json
  client/src/apis/apis.js
  client/src/components/search.js
  client/src/pages/SearchResult.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
  client/src/reduxstore/slices/intinitiSlice.js
  client/src/reduxstore/slices/sub/LibrarySlice.js
  client/src/reduxstore/store.js
Labels: [FE]김서연, ♻️ refactor

#169 [Client] 마이페이지 구매내역 상세보기 fixed
  client/src/components/mains/ImgSlider.js
  client/src/components/mypages/Like.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/search.js
  client/src/pages/Register.js
  client/src/pages/SearchResult.js
  client/src/pages/SubCategory.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Library.js
  client/src/reduxstore/slices/myOrderSlice.js
Labels: [FE]노경민, ✨ feature

#171 [Client] 판매등록페이지 반응형및 사진삭제버튼 수정
  README.md
  client/src/pages/Register.js
Labels: [FE]노경민, ✨ feature, 🎨 style

#173 ✨ feat : 주문 상세보기 추가
  server/src/main/java/gohome/dailydaily/domain/order/controller/OrderController.java
  server/src/main/java/gohome/dailydaily/domain/order/service/OrderService.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
Labels: [BE]허준열, ✨ feature

#172 [Client] 무한스크롤 및 검색 수정
  client/src/App.js
  client/src/components/CartItem.js
  client/src/imgs/noImg.gif
  client/src/pages/SearchResult.js
  client/src/pages/ShoppingCart.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/sub/LivingroomSlice.js
  client/src/reduxstore/slices/sub/bedrommSlice.js
  client/src/reduxstore/slices/sub/kitchenSlice.js
  client/src/reduxstore/slices/subCategorySlice.js
  client/src/reduxstore/store.js
Labels: [FE]김서연, ♻️ refactor

#170 🚀 deploy: Github Actions 을 이용한 자동배포
  .github/ISSUE_TEMPLATE/feature-issues-default.md
  .github/workflows/gradle.yml
  server/appspec.yml
  server/gradlew
  server/scripts/deploy.sh
  server/src/main/java/gohome/dailydaily/domain/file/repository/LocalFileRepository.java
  server/src/main/java/gohome/dailydaily/global/config/AWSConfig.java
  server/src/main/resources/application.yml
Labels: [BE]홍승재, 🚀 deploy

#181 [Client] 피드백
  client/.env
  client/public/_redirects
  client/src/components/Header.js
  client/src/components/mains/NewProducts.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/Like.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/Register.js
  client/src/pages/ShoppingCart.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]노경민, ✨ feature, 🎨 style

#182 [Client] 멘토링 피드백 적용중
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/mypages/Like.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/search.js
  client/src/pages/Login.js
  client/src/pages/Register.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/sub/Bedroom.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/likeSlice.js
  client/src/reduxstore/slices/myOrderSlice.js
  client/src/reduxstore/slices/reviewSlice.js
Labels: [FE]임세영, 🐞bug, ♻️ refactor, 🎨 style

#184 [Client] 멘토링 피드백 적용
  client/package-lock.json
  client/package.json
  client/src/apis/apis.js
  client/src/components/mypages/Like.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/useIntersect.js
  client/src/pages/Login.js
  client/src/pages/Register.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]임세영, 🎨 style

#185 [Client] 깃허브 머지중 충돌로 날아간 파일 수정 및 상세페이지 좋아요 요청 추가
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Login.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, 🐞bug

#186 [Client] 소분류 리팩토링 & 로딩아이콘 제작
  client/src/App.js
  client/src/GlobalStyles.js
  client/src/components/DropDown.js
  client/src/components/Header.js
  client/src/components/LoadingIcon.js
  client/src/components/mains/NewProducts.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/search.js
  client/src/components/subcategories/SubCalousel.js
  client/src/components/subcategories/goods.js
  client/src/imgs/sub-bed1.jpeg
  client/src/imgs/sub-kitchen.png
  client/src/imgs/sub-library2.jpeg
  client/src/imgs/sub-living1.jpeg
  client/src/pages/Login.js
  client/src/pages/Mypage.js
  client/src/pages/SearchResult.js
  client/src/pages/Signup.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
Labels: [FE]김서연, ♻️ refactor

#187 [Client]css 수정 및 마이페이지 최근 본 상품 삭제
  client/src/App.js
  client/src/GlobalStyles.js
  client/src/components/Header.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/Register.js
  client/src/pages/SearchResult.js
  client/src/pages/ShoppingCart.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Library.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]노경민, ✨ feature

#183 🐛 fix : ProductService > getProductListByTitle 없는 내용 검색 시 인기 검색어 반영 안되도록 변경
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/like/controller/LikeController.java
  server/src/main/java/gohome/dailydaily/domain/like/service/LikeService.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
  server/src/main/java/gohome/dailydaily/global/common/security/controller/AuthController.java
  server/src/main/resources/application-server.yml
  server/src/test/java/gohome/dailydaily/domain/like/controller/LikeControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]허준열

#189 🐛 fix : SecurityConfig 권한 수정
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
Labels: [BE]김경근, 🐞bug

#190 [Client] 장바구니 모바일 반응형 대응
  client/src/GlobalStyles.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/ShoppingCart.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]김서연

#191 [Client] css 이상한부분 수정
  client/src/components/Button.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Login.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
Labels: [FE]임세영, 🎨 style

#192 🐞 bug: Custom Domain CORS 설정
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
Labels: 🐞bug

#193 :bug: fix : SecurityConfig 권한 수정
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
Labels: [BE]김경근, 🐞bug

#194 ✨ feat: DTO 유효성 검증 추가
  server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/file/controller/FileController.java
  server/src/main/java/gohome/dailydaily/domain/like/controller/LikeController.java
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
  server/src/main/java/gohome/dailydaily/domain/member/service/MemberService.java
  server/src/main/java/gohome/dailydaily/domain/order/controller/OrderController.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/OptionDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
  server/src/main/resources/application-server.yml
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]홍승재, [BE]김경근, ✨ feature

#196 [Client] 피드백수정
  client/src/GlobalStyles.js
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/Header.js
  client/src/components/Star.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Register.js
  client/src/pages/ShoppingCart.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, ♻️ refactor, 🎨 style

#180 Update README.md
  README.md
Labels: 📝docs

#198 [Client] 피드백 수정
  client/src/GlobalStyles.js
  client/src/components/Alert.js
  client/src/components/Header.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/Pagination.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Mypage.js
  client/src/pages/Register.js
  client/src/pages/SearchResult.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]노경민, ✨ feature

#202 ✨ feat : 인기 검색어 로직 변경
  server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchRedisRepository.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchResRedisRepository.java
  server/src/main/java/gohome/dailydaily/domain/search/scheduler/SearchScheduler.java
  server/src/test/java/gohome/dailydaily/domain/search/controller/SearchControllerTest.java
Labels: [BE]김경근, ✨ feature

#203 [Client] 피드백수정 및 alert 수정
  client/src/GlobalStyles.js
  client/src/components/Alert.js
  client/src/components/mains/BrandProductDetail.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/Pagination.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Mypage.js
  client/src/pages/Register.js
  client/src/pages/SearchResult.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/obsever.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, 🐞bug, 🎨 style

#204 [Client] css 수정
  client/public/index.html
  client/src/GlobalStyles.js
  client/src/components/CartItem.js
  client/src/components/Fadein.js
  client/src/components/Header.js
  client/src/components/mains/NewProductDetail.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/search.js
  client/src/pages/Main.js
  client/src/pages/SearchResult.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]노경민, ✨ feature

#206 [Client] 검색창 리팩토링
  client/public/index.html
  client/src/App.js
  client/src/GlobalStyles.js
  client/src/components/CartItem.js
  client/src/components/Header.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/search.js
  client/src/pages/Login.js
  client/src/pages/Register.js
  client/src/pages/SearchResult.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
  client/src/pages/sub/obsever.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]김서연, ♻️ refactor

#207 :bug: fix : 로깅 로직 수정 & 서버 상태 확인 로깅 추가
  server/src/main/java/gohome/dailydaily/domain/search/scheduler/SearchScheduler.java
  server/src/main/java/gohome/dailydaily/global/error/logging/DiscordWebhook.java
  server/src/main/java/gohome/dailydaily/global/error/logging/ServerErrorLogging.java
  server/src/main/resources/application-server.yml
  server/src/test/resources/application.yml
Labels: [BE]김경근, 🐞bug

#208 🐛 fix : 로깅 수정
  server/src/main/java/gohome/dailydaily/domain/search/scheduler/SearchScheduler.java
  server/src/main/java/gohome/dailydaily/global/error/logging/DiscordWebhook.java
  server/src/main/java/gohome/dailydaily/global/error/logging/ServerErrorLogging.java
  server/src/test/java/gohome/dailydaily/util/security/SecurityTestConfig.java
Labels: [BE]김경근, 🐞bug

#209 ✨ feat : 로깅 user-agent 추가
  server/src/main/java/gohome/dailydaily/global/error/logging/DiscordWebhook.java
  server/src/main/java/gohome/dailydaily/global/error/logging/ServerErrorLogging.java
Labels: [BE]김경근, ✨ feature

#210 🐛 fix : Ip 127.0.0.1 제외
  server/src/main/java/gohome/dailydaily/domain/search/scheduler/SearchScheduler.java
  server/src/main/java/gohome/dailydaily/global/error/logging/ServerErrorLogging.java
Labels: [BE]김경근, 🐞bug, ♻️ refactor

#201 📝docs: readme 수정
  README.md
Labels: 📝docs

#211 ♻️ refactor: OrderProduct 테이블명 수정
  server/src/main/java/gohome/dailydaily/domain/order/entity/OrderProduct.java
  server/src/main/java/gohome/dailydaily/domain/search/scheduler/SearchScheduler.java
  server/src/main/java/gohome/dailydaily/global/error/logging/ServerErrorLogging.java
Labels: 🐞bug
