Repository codestates-seb/seb40_main_013, pull requests merged in 2022-11, with the labels that each got.

#16 [BE] 연관관계 매핑 수정
  server/build.gradle
  server/src/main/java/gohome/dailydaily/domain/cart/entity/Cart.java
  server/src/main/java/gohome/dailydaily/domain/like/entity/Like.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/Member.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/Seller.java
  server/src/main/java/gohome/dailydaily/domain/order/entity/Order.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/review/entity/Review.java
Labels: [BE]김경근, 🐞bug

#18 [Client] Footer 기능 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/GlobalStyled.js
  client/src/components/Footer.js
  client/src/index.js
  client/src/page/Signup/SignupBuyer.js
  client/src/page/Signup/SignupSeller.js
Labels: [FE]임세영, ✨ feature

#19 [Client] Header 구현
  client/package-lock.json
  client/package.json
  client/public/bed.png
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/GlobalStyled.js
  client/src/GlobalStyles.js
  client/src/components/headers/Header.js
  client/src/components/headers/logo.png
  client/src/index.js
Labels: [FE]김서연, ✨ feature

#20 [Client] 로그인페이지 뼈대 생성
  client/package-lock.json
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css
  client/src/App.test.js
  client/src/index.css
  client/src/logo.svg
  client/src/pages/Login.js
  client/src/pages/signup/SignupBuyer.js
  client/src/pages/signup/SignupSeller.js
  client/src/setupTests.js
Labels: [FE]노경민, ✨ feature

#23 ✨ feat : Exception 처리 기능 구현
  server/src/main/java/gohome/dailydaily/global/error/BusinessLogicException.java
  server/src/main/java/gohome/dailydaily/global/error/ErrorResponse.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/main/java/gohome/dailydaily/global/error/GlobalExceptionAdvice.java
Labels: [BE]홍승재, ✨ feature

#24 ✨ feat : 회원 관련 기능
  server/src/main/java/gohome/dailydaily/DailydailyApplication.java
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/Member.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/MemberStatus.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/Seller.java
  server/src/main/java/gohome/dailydaily/domain/member/mapper/MemberMapper.java
  server/src/main/java/gohome/dailydaily/domain/member/mapper/SellerMapper.java
  server/src/main/java/gohome/dailydaily/domain/member/repository/MemberRepository.java
  server/src/main/java/gohome/dailydaily/domain/member/repository/SellerRepository.java
  server/src/main/java/gohome/dailydaily/domain/member/service/MemberService.java
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
  server/src/main/java/gohome/dailydaily/global/common/security/controller/LoginController.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAccessDeniedHandler.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationEntryPoint.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/ErrorResponder.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/test/java/gohome/dailydaily/domain/member/service/MemberServiceTest.java
Labels: [BE]김경근, ✨ feature

#25 [Client] 메인페이지 뼈대완료, 라우팅, 제이슨파일생성
  client/data.json
  client/data/data.json
  client/package-lock.json
  client/package.json
  client/public/manifest.json
  client/src/App.js
  client/src/components/Button.js
  client/src/components/headers/Header.js
  client/src/components/mains/Calousel.js
  client/src/components/mains/Product.js
  client/src/imgs/2단 서랍.png
  client/src/imgs/2단 장식장.png
  client/src/imgs/4단서랍.png
  client/src/imgs/carousel1.png
  client/src/imgs/carousel2.png
  client/src/imgs/carousel3.png
  client/src/imgs/carousel4.png
  client/src/imgs/오픈 장식장.png
  client/src/imgs/화장대.png
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
Labels: [FE]노경민, ✨ feature

#27 [Client] 상세 페이지 뼈대 , 리뷰 뼈대 구현
  client/package-lock.json
  client/src/App.js
  client/src/GlobalStyles.js
  client/src/imgs/리뷰이미지.jpeg
  client/src/imgs/리뷰이미지2.jpeg
  client/src/imgs/일로 크롬 오피스 체어.jpeg
  client/src/imgs/일룸 오피스 체어2.jpeg
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/pages/signup/SignupSeller.js
Labels: [FE]임세영, ✨ feature

#28 [Client] 회원가입 페이지 구현
  client/data/data.json
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Footer.js
  client/src/components/effectivenessCheck.js
  client/src/components/headers/Header.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
Labels: [FE]임세영, ✨ feature

#31 [Client] login 페이지 뼈대 변경, Signup axios 기능추가, 리덕스툴킷 설치 및 구조작업
  client/data.json
  client/data/data.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/effectivenessCheck.js
  client/src/imgs/chairImage.png
  client/src/index.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/userSlice.js
  client/src/reduxstore/store.js
Labels: [FE]임세영, ✨ feature

#30 ✨ feat : JWT 토큰 인증 / 로그인
  server/build.gradle
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/Member.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/MemberRole.java
  server/src/main/java/gohome/dailydaily/domain/member/repository/MemberRepository.java
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
  server/src/main/java/gohome/dailydaily/global/common/security/controller/LoginController.java
  server/src/main/java/gohome/dailydaily/global/common/security/dto/LoginDto.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/CustomFilterConfigurer.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAccessDeniedHandler.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationEntryPoint.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationFailureHandler.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationSuccessHandler.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/ErrorResponder.java
  server/src/main/java/gohome/dailydaily/global/common/security/provider/CustomAuthenticationProvider.java
  server/src/main/java/gohome/dailydaily/global/common/security/resolver/MemberId.java
  server/src/main/java/gohome/dailydaily/global/common/security/resolver/MemberIdResolver.java
  server/src/main/java/gohome/dailydaily/global/common/security/util/CustomAuthorityUtils.java
  server/src/main/java/gohome/dailydaily/global/common/security/util/CustomUserDetails.java
  server/src/main/java/gohome/dailydaily/global/common/security/util/JwtTokenizer.java
  server/src/main/java/gohome/dailydaily/global/config/WebConfig.java
  server/src/main/resources/application.yml
Labels: [BE]김경근, ✨ feature

#38 Featmain
  client/data.json
  client/data/data.json
  client/src/components/headers/Header.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PurchaseList.js
  client/src/imgs/star.png
  client/src/pages/Main.js
  client/src/pages/Mypage.js
Labels: [FE]노경민, ✨ feature

#39 [Client] 장바구니 구현
  client/src/GlobalStyles.js
  client/src/components/Header.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/ShoppingCart.js
Labels: [FE]김서연, ✨ feature

#36 ✅ test : Security Test
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
  server/src/main/java/gohome/dailydaily/global/common/security/controller/LoginController.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/CustomFilterConfigurer.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/member/service/MemberServiceTest.java
  server/src/test/java/gohome/dailydaily/util/Reflection.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/java/gohome/dailydaily/util/security/SecurityTestConfig.java
  server/src/test/java/gohome/dailydaily/util/security/WithMockCustomUser.java
  server/src/test/java/gohome/dailydaily/util/security/WithMockCustomUserSecurityContextFactory.java
Labels: [BE]김경근, ✅ test

#37 ✨feat: File 업로드 기능 구현
  server/.gitignore
  server/img/productImg/black.jpg
  server/img/profileImg/black.jpg
  server/src/main/generated/gohome/dailydaily/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/gohome/dailydaily/domain/member/mapper/SellerMapperImpl.java
  server/src/main/java/gohome/dailydaily/domain/file/config/FileConfig.java
  server/src/main/java/gohome/dailydaily/domain/file/controller/FileController.java
  server/src/main/java/gohome/dailydaily/domain/file/entity/File.java
  server/src/main/java/gohome/dailydaily/domain/file/repository/FileRepository.java
  server/src/main/java/gohome/dailydaily/domain/file/repository/LocalFileRepository.java
  server/src/main/java/gohome/dailydaily/domain/file/repository/S3FileRepository.java
  server/src/main/java/gohome/dailydaily/domain/file/service/FileService.java
  server/src/main/resources/application.yml
  server/src/test/java/gohome/dailydaily/domain/file/FileServiceTest.java
  server/src/test/java/gohome/dailydaily/domain/file/WebIntegrationTest.java
Labels: [BE]홍승재, ✨ feature

#42 [Client] 헤더 디자인 변경
  client/src/GlobalStyles.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/pages/Main.js
  client/src/pages/ShoppingCart.js
Labels: [FE]김서연, ✨ feature

#43 ✨ feat : 상품 조회 기능 추가
  server/build.gradle
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/OptionDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/SelectDto.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Category.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Option.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/CategoryRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/service/CategoryService.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
Labels: [BE]허준열, ✨ feature

#45 [Client] 로그인 토큰 재갱신 구현
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/pages/Main.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, ✨ feature

#47 [Client] 검색 모달 구현
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/search.js
  client/src/pages/Main.js
Labels: [FE]김서연, ✨ feature

#48 ✨ feat : 회원 정보 조회 기능 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/java/gohome/dailydaily/util/security/WithMockCustomUserSecurityContextFactory.java
Labels: [BE]김경근, ✨ feature

#50 [Client] 로그인, 푸터 반응형 css 구현
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/pages/Login.js
  client/src/pages/Main.js
Labels: [FE]임세영, 🎨 style

#49 ✨ feat : 리뷰 관련 기능 추가
  server/src/main/java/gohome/dailydaily/domain/review/controller/ReviewController.java
  server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
  server/src/main/java/gohome/dailydaily/domain/review/entity/Review.java
  server/src/main/java/gohome/dailydaily/domain/review/mapper/ReviewMapper.java
  server/src/main/java/gohome/dailydaily/domain/review/repository/ReviewRepository.java
  server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/main/java/gohome/dailydaily/global/error/GlobalExceptionAdvice.java
Labels: [BE]김경근, ✨ feature

#53 [client] 소분류 페이지 스타일 변경
  client/src/components/CartItem.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/mains/Product.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
  client/src/pages/SubCategory.js
Labels: [FE]김서연, ✨ feature

#54 [Client] 메인페이지 뼈대 수정
  client/data/data.json
  client/src/components/mains/BrandProducts.js
  client/src/components/mains/Calousel2.js
  client/src/components/mains/ImgSlider.js
  client/src/components/mains/Product.js
  client/src/imgs/brandImg.png
  client/src/imgs/carousel1.png
  client/src/imgs/carousel2.png
  client/src/imgs/carousel3.png
  client/src/imgs/carousel4.png
  client/src/imgs/carousel5.png
  client/src/imgs/desker.png
  client/src/imgs/dodot.jpeg
  client/src/imgs/forthehome.png
  client/src/imgs/sofsys.jpeg
  client/src/pages/Main.js
Labels: [FE]노경민, ✨ feature

#59 [Client] 헤더 상단고정 , 반응형 css구현중
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]임세영, ✨ feature, 🎨 style

#58 ✨ feat : 작성한 리뷰 조회
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/Member.java
  server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
  server/src/main/java/gohome/dailydaily/domain/review/mapper/ReviewMapper.java
  server/src/main/java/gohome/dailydaily/domain/review/repository/ReviewRepository.java
  server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
  server/src/main/java/gohome/dailydaily/global/common/dto/PageResponseDto.java
  server/src/main/java/gohome/dailydaily/global/common/dto/SliceResponseDto.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]김경근, ✨ feature

#60 [Client] 회원가입 반응형 css 구현 피드백 대기중
  client/src/components/Footer.js
  client/src/pages/Login.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/SubCategory.js
Labels: [FE]임세영, 🎨 style

#61 [Client] 메인페이지 반응형 일부 추가, best of best 아랫부분 추가
  client/data/data.json
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/mains/BrandProducts.js
  client/src/components/mains/Calousel2.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
Labels: [FE]노경민, ✨ feature, 🎨 style

#62 [Client] 카테고리 드롭다운 구현 및 상세 수정
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/search.js
  client/src/components/subcategories/SubCalousel.js
  client/src/pages/Main.js
  client/src/pages/ShoppingCart.js
  client/src/pages/SubCategory.js
Labels: [FE]김서연, ✨ feature, 🎨 style

#63 ✨ feat : 장바구니 상품 추가 기능 구현 및 테스트
  server/.gitignore
  server/src/docs/asciidoc/index.adoc
  server/src/main/generated/gohome/dailydaily/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/gohome/dailydaily/domain/member/mapper/SellerMapperImpl.java
  server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/CartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/entity/Cart.java
  server/src/main/java/gohome/dailydaily/domain/cart/entity/ProductCart.java
  server/src/main/java/gohome/dailydaily/domain/cart/mapper/CartMapper.java
  server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
  server/src/main/java/gohome/dailydaily/domain/cart/repository/CartRepository.java
  server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
  server/src/main/java/gohome/dailydaily/domain/file/entity/File.java
  server/src/main/java/gohome/dailydaily/domain/file/repository/LocalFileRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/review/repository/ReviewRepository.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/CustomTest.java
  server/src/test/java/gohome/dailydaily/domain/cart/controller/CartControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/cart/repository/CartRepositoryTest.java
  server/src/test/java/gohome/dailydaily/domain/cart/service/CartServiceTest.java
  server/src/test/java/gohome/dailydaily/domain/file/FileServiceTest.java
  server/src/test/java/gohome/dailydaily/domain/file/WebIntegrationTest.java
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]홍승재, 📝docs, ✨ feature, ✅ test

#64 ✨ feat : 장바구니 상품 삭제 기능 구현 및 API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
  server/src/main/java/gohome/dailydaily/domain/cart/repository/ProductCartRepository.java
  server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/cart/controller/CartControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/cart/service/CartServiceTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]홍승재, 📝docs, ✨ feature

#67 [Client] mypage 반응형및 뼈대 추가
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/mains/BrandProductDetail.js
  client/src/components/mains/Calousel2.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/search.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
Labels: [FE]노경민, ✨ feature

#68 ✨ feat : 장바구니 조회 구현 및 API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/CartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/mapper/CartMapper.java
  server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
  server/src/main/java/gohome/dailydaily/domain/cart/repository/CartRepository.java
  server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/cart/controller/CartControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/cart/service/CartServiceTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]홍승재, 📝docs, ✨ feature

#69 [Client] api get요청 자동갱신 오류로 진행중
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/mypages/MyReview.js
  client/src/components/search.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
  client/src/reduxstore/store.js
Labels: [FE]임세영, 🐞bug

#70 💚 chore : AWS 배포파일 생성
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: [BE]홍승재

#72 ✨ feat : Review Response > nickname, createdAt, modifiedAt 추가
  server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
  server/src/main/java/gohome/dailydaily/domain/review/mapper/ReviewMapper.java
  server/src/main/java/gohome/dailydaily/global/common/security/resolver/MemberIdResolver.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]김경근, ✨ feature

#73 ♻️ refactor : 상품 카테고리별 조회 동적 할당 코드 리팩토링
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/dto/GetProductListByCategoryDTO.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/OptionDto.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/CategoryRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustom.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/param/CategoryGetParam.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/global/common/dto/PagingRequestDto.java
  server/src/main/java/gohome/dailydaily/global/util/Querydsl4RepositorySupport.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]허준열, 📝docs, ♻️ refactor

#77 ✨ feat : 장바구니 조회 및 수정 기능 구현, API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/entity/ProductCart.java
  server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
  server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/cart/controller/CartControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/cart/service/CartServiceTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]홍승재, 📝docs, ✨ feature, ✅ test

#75 ✨ feat : Password 검증 API, 게스트 로그인 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/global/common/security/controller/AuthController.java
  server/src/main/java/gohome/dailydaily/global/common/security/controller/RefreshController.java
  server/src/main/java/gohome/dailydaily/global/common/security/dto/PasswordDto.java
  server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/global/common/security/controller/AuthControllerTest.java
  server/src/test/java/gohome/dailydaily/global/common/security/service/PasswordEncoderTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]김경근, ✨ feature

#79 [Client]Style/subcategory
  client/src/components/CartItem.js
  client/src/components/Header.js
  client/src/components/search.js
  client/src/components/subcategories/SubCalousel.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/SubCategory.js
Labels: [FE]김서연, ✨ feature, 🎨 style

#78 ♻️ refactor : JwtTokenizer > 토큰 생성 메서드 추가
  server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
  server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/RefreshVerificationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
  server/src/main/java/gohome/dailydaily/global/common/security/util/JwtTokenizer.java
Labels: [BE]김경근, ✨ feature

#80 ✨ feat : 메인 페이지 방문 시 상품 정보 요청 API 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
  server/src/main/java/gohome/dailydaily/domain/member/repository/SellerRepository.java
  server/src/main/java/gohome/dailydaily/domain/member/service/MemberService.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/CategoryRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustom.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/main/java/gohome/dailydaily/domain/product/service/CategoryService.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
  server/src/main/java/gohome/dailydaily/global/util/Querydsl4RepositorySupport.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/domain/cart/controller/CartControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]허준열, 📝docs, ✨ feature

#74 ✨ feat : File S3 업로드 코드 구현
  server/build.gradle
  server/src/main/java/gohome/dailydaily/domain/file/config/FileConfig.java
  server/src/main/java/gohome/dailydaily/domain/file/repository/LocalFileRepository.java
  server/src/main/java/gohome/dailydaily/domain/file/repository/S3FileRepository.java
  server/src/main/resources/application.yml
  server/src/test/resources/application.yml
Labels: [BE]홍승재, ✨ feature

#81 fix : 정규표현식 수정
  server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/dto/GetProductListByTitleDto.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustom.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/param/TitleGetParam.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]허준열, 🐞bug

#83 [Client] 게스트로그인 구현완료 , 마이리뷰 조회 뼈대 or 기능, 추가 뼈대 or 기능, 삭제 뼈대 or 기능 구현완료 , 상세페이지 장바구니추가 기능완료
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/components/Star.js
  client/src/components/effectivenessCheck.js
  client/src/components/mains/Product.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/search.js
  client/src/pages/Login.js
  client/src/pages/Mypage.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, 🐞bug, 📝docs, ✨ feature

#84 ♻️ refactor : 메인 페이지 조회 시 브랜드 명, 카테고리 전송
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]허준열, ♻️ refactor

#85 Fix: S3 파일 업로드 기능 수정
  server/src/main/java/gohome/dailydaily/global/config/AWSConfig.java
Labels: [BE]홍승재, 🐞bug

#86 [Client] mypage, main 기능 구현
  client/package-lock.json
  client/src/apis/apis.js
  client/src/components/effectivenessCheck.js
  client/src/components/mains/BrandProducts.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/mainSlice.js
  client/src/reduxstore/slices/userSlice.js
  client/src/reduxstore/store.js
Labels: [FE]노경민, ✨ feature

#88 [client] 장바구니 기능구현
  client/src/App.js
  client/src/GlobalStyles.js
  client/src/components/CartItem.js
  client/src/components/Header.js
  client/src/components/mains/Product.js
  client/src/components/search.js
  client/src/pages/Main.js
  client/src/pages/ShoppingCart.js
  client/src/pages/SubCategory.js
Labels: [FE]김서연, ✨ feature, ♻️ refactor

#90 [Client]마이페이지 redux 연결
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/components/mains/BrandProducts.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/Recent.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]노경민, ✨ feature

#89 🐛 fix : product content 응답 수정
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]홍승재, 🐞bug

#91 [Client] axios get, delete 재요청 안되던부분 수정
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PostReview.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, 🐞bug

#93 [Client] 코드 간소화
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]임세영, 🐞bug

#96 [Client] footer 하단고정
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]임세영, 🐞bug

#94 ✨ feat : 인기 검색어 API 구현
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
  server/src/main/java/gohome/dailydaily/domain/search/dto/SearchDto.java
  server/src/main/java/gohome/dailydaily/domain/search/mapper/SearchMapper.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchRedisRepository.java
  server/src/main/java/gohome/dailydaily/global/config/EmbeddedRedisConfig.java
  server/src/main/java/gohome/dailydaily/global/config/RedisRepositoryConfig.java
  server/src/test/java/gohome/dailydaily/domain/search/controller/SearchControllerTest.java
Labels: [BE]김경근, ✨ feature

#98 [Client] 장바구니 기능, 리덕스 툴킷으로 리팩토링
  client/src/apis/apis.js
  client/src/components/CartItem.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/mains/Product.js
  client/src/pages/ShoppingCart.js
  client/src/pages/SubCategory.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]김서연, ♻️ refactor, 🎨 style

#100 :green_heart: chore : Redis Setting 수정
  server/src/main/java/gohome/dailydaily/global/config/EmbeddedRedisConfig.java
  server/src/main/java/gohome/dailydaily/global/config/RedisRepositoryConfig.java
  server/src/main/resources/application-server.yml
Labels: [BE]김경근

#95 ✨ feat : 조건별 정렬 추가
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustom.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/param/CategoryGetParam.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/global/common/dto/PagingRequestDto.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]허준열, ✨ feature

#101 [Client] 메인페이지 데이터 다시 받아와서 렌더링
  client/src/apis/apis.js
  client/src/components/Button.js
  client/src/components/mains/NewProducts.js
  client/src/pages/Main.js
  client/src/pages/SubCategory.js
  client/src/reduxstore/slices/categorySlice.js
  client/src/reduxstore/slices/mainSlice.js
Labels: [FE]노경민, 🐞bug

#104 Refactor/shopcart
  client/src/apis/apis.js
  client/src/components/CartItem.js
  client/src/pages/ShoppingCart.js
  client/src/pages/SubCategory.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/subCategorySlice.js
  client/src/reduxstore/store.js
Labels: [FE]김서연, ♻️ refactor

#107 [Client] product.js css 수정
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/components/mains/NewProducts.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/pages/Main.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]노경민, ✨ feature

#102 ✨ feat : 로그인 - 상태 유지 추가 / 게스트 로그인 - 권한, 아이디 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/global/common/security/dto/LoginDto.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
  server/src/main/java/gohome/dailydaily/global/common/security/util/JwtTokenizer.java
  server/src/main/resources/application.yml
  server/src/test/java/gohome/dailydaily/global/common/security/controller/LoginControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: [BE]김경근, ✨ feature

#109 ✨ feat : Guest 로그인 RefreshToken 추가
  server/src/main/java/gohome/dailydaily/global/common/security/controller/AuthController.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
  server/src/main/java/gohome/dailydaily/global/common/security/util/JwtTokenizer.java
  server/src/test/java/gohome/dailydaily/global/common/security/controller/AuthControllerTest.java
Labels: [BE]김경근, ✨ feature

#111 [Client]메인페이지 브랜드 탭 스크롤 구현완료, 이미지폴더 정리
  client/data/data.json
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/components/ScrollToTop.js
  client/src/components/mains/NewProducts.js
  client/src/components/mains/Product.js
  client/src/imgs/2단 서랍.png
  client/src/imgs/2단 장식장.png
  client/src/imgs/4단서랍.png
  client/src/imgs/brandImg.png
  client/src/imgs/chair2.png
  client/src/imgs/chair3.png
  client/src/imgs/chair4.png
  client/src/imgs/desker.png
  client/src/imgs/dodot.jpeg
  client/src/imgs/forthehome.png
  client/src/imgs/logo.png
  client/src/imgs/sofsys.jpeg
  client/src/imgs/오픈 장식장.png
  client/src/imgs/화장대.png
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
Labels: [FE]노경민, ✨ feature

#112 [Client] 소분류 페이지 상품 반응형 적용
  client/src/GlobalStyles.js
  client/src/apis/apis.js
  client/src/components/CartItem.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/pages/ShoppingCart.js
  client/src/pages/SubCategory.js
  client/src/reduxstore/slices/subCategorySlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]김서연, 🎨 style

#113 [Client] 마이페이지 정보수정페이지 반응형및 수정하는법 추가
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/GlobalStyles.js
  client/src/apis/apis.js
  client/src/components/mains/BrandProductDetail.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
Labels: [FE]노경민, ✨ feature

#114 [Client] 1차 배포 피드백 수정
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/ScrollToTop.js
  client/src/components/mains/Calousel2.js
  client/src/components/mains/Product.js
  client/src/components/mypages/Recent.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/SubCategory.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/mainCategorySlice.js
  client/src/reduxstore/slices/mainSlice.js
  client/src/reduxstore/slices/subCategorySlice.js
  client/src/reduxstore/slices/userSlice.js
  client/src/reduxstore/store.js
Labels: [FE]임세영, 🐞bug, 📝docs, 🎨 style

#116 [Client] 헤더 높이 변경에 따른 각 페에지 margin-top 수정
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Header.js
  client/src/components/search.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/SubCategory.js
Labels: [FE]김서연, 🎨 style

#117 ✨ feat : 회원 프로필 이미지 추가 및 주문 생성 시 판매량, 재고 업데이트
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
  server/src/main/java/gohome/dailydaily/domain/member/entity/Member.java
  server/src/main/java/gohome/dailydaily/domain/member/service/MemberService.java
  server/src/main/java/gohome/dailydaily/domain/order/controller/OrderController.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
  server/src/main/java/gohome/dailydaily/domain/order/entity/Order.java
  server/src/main/java/gohome/dailydaily/domain/order/mapper/OrderMapper.java
  server/src/main/java/gohome/dailydaily/domain/order/service/OrderService.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Option.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/order/controller/OrderControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/order/service/OrderServiceTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]홍승재, ✨ feature, ♻️ refactor

#115 ✨ feat : 리뷰 등록 시 상품 평점 변경
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
  server/src/test/java/gohome/dailydaily/domain/order/repository/OrderRepositoryTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]허준열

#121 [Client] product.js 반응형 구현, 메인페이지 피드백반영, 마이페이지 탈퇴버튼 수정
  client/src/apis/apis.js
  client/src/components/Button.js
  client/src/components/mains/Calousel.js
  client/src/components/mains/Calousel2.js
  client/src/components/mains/NewProducts.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
Labels: [FE]노경민, 🐞bug, ✨ feature

#123 [client] 장바구니 : 화면 크기에 따른 반응형 적용
  .github/ISSUE_TEMPLATE/feature-issues-default.md
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/CartItem.js
  client/src/components/Header.js
  client/src/components/mains/NewProducts.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/SubCategory.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/sub/LibrarySlice.js
  client/src/reduxstore/slices/sub/LivingroomSlice.js
  client/src/reduxstore/slices/sub/bedrommSlice.js
  client/src/reduxstore/slices/sub/kitchenSlice.js
  client/src/reduxstore/slices/subCategorySlice.js
  client/src/reduxstore/store.js
Labels: [FE]김서연, 🎨 style

#120 ✨ feat : Review 사진 등록 기능 구현
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/review/controller/ReviewController.java
  server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
  server/src/main/java/gohome/dailydaily/domain/review/entity/Review.java
  server/src/main/java/gohome/dailydaily/domain/review/mapper/ReviewMapper.java
  server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]김경근, ✨ feature

#125 🐛 fix: 주문, 장바구니 API 응답 수정
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderProductDto.java
  server/src/main/java/gohome/dailydaily/domain/order/mapper/OrderMapper.java
  server/src/main/resources/application-server.yml
  server/src/test/java/gohome/dailydaily/domain/order/controller/OrderControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
  server/src/test/resources/application.yml
Labels: enhancement, [BE]홍승재

#124 [Client] 디테일 반응형 수정중
  client/.gitignore
  client/package-lock.json
  client/public/index.html
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/Button.js
  client/src/components/CartItem.js
  client/src/components/Footer.js
  client/src/components/effectivenessCheck.js
  client/src/components/mains/BrandProductDetail.js
  client/src/components/mains/Calousel2.js
  client/src/components/mains/NewProducts.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/ProfileImg.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, 🎨 style

#126 [Client] 마이페이지 구매내역 상세보기부분 추가/스크롤 탑버튼 fix/ 버튼 hover 추가
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/Button.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Mypage.js
  client/src/pages/SubCategory.js
  client/src/reduxstore/slices/myOrderSlice.js
  client/src/reduxstore/store.js
Labels: [FE]노경민, ✨ feature

#127 :bug: fix : 주문 생성 오류 해결
  server/src/main/java/gohome/dailydaily/domain/order/entity/OrderProduct.java
  server/src/main/java/gohome/dailydaily/domain/order/mapper/OrderProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/order/service/OrderService.java
Labels: [BE]김경근, 🐞bug

#129 🐛 fix : Order Test 및 주문번호 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
  server/src/main/java/gohome/dailydaily/domain/order/mapper/OrderMapper.java
  server/src/test/java/gohome/dailydaily/domain/order/controller/OrderControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/order/service/OrderServiceTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]홍승재, 🐞bug, ✅ test

#128 ✨ feat : 브랜드, 제목 검색, 카테고리 제품 총 수량 api 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustom.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
  server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
  server/src/test/java/gohome/dailydaily/domain/order/repository/OrderRepositoryTest.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]허준열, 📝docs, ✨ feature

#130 [Client] 리뷰사진등록 추가, docs 수정, sweet alert 추가
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/Button.js
  client/src/components/CartItem.js
  client/src/components/Header.js
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Login.js
  client/src/pages/Mypage.js
  client/src/pages/ShoppingCart.js
  client/src/pages/Signup.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, 📝docs, ✨ feature, 🎨 style

#132 [Client] 검색 결과창 구현 및 카테고리별 상품 데이터 나열중
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/mains/NewProducts.js
  client/src/components/mains/Product.js
  client/src/components/mypages/EditProfile.js
  client/src/components/search.js
  client/src/components/subcategories/DropDown.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/SearchResult.js
  client/src/pages/ShoppingCart.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
  client/src/reduxstore/slices/sub/LibrarySlice.js
Labels: [FE]김서연, ✨ feature, ♻️ refactor, 🎨 style

#134 ✨ feat : 상품 추가 API 구현
  server/src/main/java/gohome/dailydaily/domain/file/repository/LocalFileRepository.java
  server/src/main/java/gohome/dailydaily/domain/member/service/SellerService.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/OptionDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Option.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/CategoryRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/service/CategoryService.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/test/resources/application.yml
Labels: [BE]허준열

#136 ✨ feat : 상품 좋아요 API 구현 및 Test 수정
  server/src/main/java/gohome/dailydaily/domain/like/controller/LikeController.java
  server/src/main/java/gohome/dailydaily/domain/like/repository/LikeRepository.java
  server/src/main/java/gohome/dailydaily/domain/like/service/LikeService.java
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderProductDto.java
  server/src/main/java/gohome/dailydaily/domain/order/service/OrderService.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]홍승재, ✨ feature

#135 [Client] 구매 생성 구현
  client/src/apis/apis.js
  client/src/components/Button.js
  client/src/components/CartItem.js
  client/src/components/Header.js
  client/src/components/search.js
  client/src/pages/SearchResult.js
  client/src/pages/ShoppingCart.js
  client/src/pages/sub/Library.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/sub/LibrarySlice.js
Labels: [FE]김서연, ✨ feature

#138 [Client] 판매상품등록페이지생성, 구매내역 구현중
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/Button.js
  client/src/components/Header.js
  client/src/components/mains/Calousel2.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Main.js
  client/src/pages/Mypage.js
  client/src/pages/Register.js
Labels: [FE]노경민, ✨ feature

#139 [Client] 리뷰등록 추가완료 css 수정예정
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/Button.js
  client/src/components/mypages/MyReview.js
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, 📝docs, ✨ feature

#140 ✅ test: 상품 좋아요 Controller Test 및 API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/like/controller/LikeController.java
  server/src/main/java/gohome/dailydaily/domain/order/service/OrderService.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/test/java/gohome/dailydaily/domain/like/controller/LikeControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]홍승재, 📝docs, ✅ test

#141 🐞bug: 좋아요 조회 및 삭제 오류 해결
  server/src/main/java/gohome/dailydaily/domain/like/repository/LikeRepository.java
  server/src/main/java/gohome/dailydaily/domain/like/service/LikeService.java
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
  server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
Labels: [BE]홍승재, 🐞bug

#143 [Client] 좋아요 기능추가
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Alert.js
  client/src/components/Header.js
  client/src/pages/Register.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/userSlice.js
Labels: [FE]임세영, ✨ feature

#142 ✨ feat : 레디스 캐시 적용
  server/build.gradle
  server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/CartDto.java
  server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
  server/src/main/java/gohome/dailydaily/domain/file/entity/File.java
  server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
  server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
  server/src/main/java/gohome/dailydaily/domain/order/controller/OrderController.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/dto/GetProductListByDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/OptionDto.java
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/domain/review/controller/ReviewController.java
  server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
  server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
  server/src/main/java/gohome/dailydaily/global/common/dto/PageResponseDto.java
  server/src/main/java/gohome/dailydaily/global/common/dto/SliceResponseDto.java
  server/src/main/java/gohome/dailydaily/global/common/security/resolver/LoginMember.java
  server/src/main/java/gohome/dailydaily/global/common/security/resolver/MemberResolver.java
  server/src/main/java/gohome/dailydaily/global/config/EmbeddedRedisConfig.java
  server/src/main/java/gohome/dailydaily/global/config/RedisCacheConfig.java
  server/src/main/java/gohome/dailydaily/global/config/RedisRepositoryConfig.java
  server/src/main/java/gohome/dailydaily/global/config/WebConfig.java
  server/src/main/resources/application-server.yml
  server/src/test/java/gohome/dailydaily/util/TestConfig.java
  server/src/test/java/gohome/dailydaily/util/TestMemberRepository.java
  server/src/test/java/gohome/dailydaily/util/security/SecurityTestConfig.java
  server/src/test/resources/application.yml
Labels: [BE]김경근, ✨ feature

#145 🐛 fix : 상품 추가 시 별점 버그 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/gohome/dailydaily/domain/file/repository/LocalFileRepository.java
  server/src/main/java/gohome/dailydaily/domain/like/repository/LikeRepository.java
  server/src/main/java/gohome/dailydaily/domain/like/service/LikeService.java
  server/src/main/java/gohome/dailydaily/domain/product/controller/ProductController.java
  server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepository.java
  server/src/main/java/gohome/dailydaily/domain/product/repository/ProductRepositoryCustomImpl.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
  server/src/main/resources/application-server.yml
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/domain/search/controller/SearchControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]허준열, 🐞bug, 📝docs, ✨ feature, ✅ test

#146 [Client] 카트 오류 수정
  client/src/apis/apis.js
  client/src/pages/Register.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]임세영, 🐞bug

#147 🐞fix: 주문 생성시 장바구니 상품 삭제
  server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
  server/src/main/java/gohome/dailydaily/domain/order/controller/OrderController.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
  server/src/main/java/gohome/dailydaily/domain/order/dto/OrderProductDto.java
  server/src/main/java/gohome/dailydaily/domain/order/entity/OrderProduct.java
  server/src/main/java/gohome/dailydaily/domain/order/service/OrderService.java
  server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchRedisRepository.java
Labels: [BE]홍승재, 🐞bug

#148 [CI/CD] Github Actions 설정
  .github/ISSUE_TEMPLATE/feature-issues-default.md
  .github/workflows/gradle.yml
Labels: [BE]홍승재

#151 [Client] 상품추가 구현 , 내가 작성한 리뷰 페이지네이션 추가
  client/src/apis/apis.js
  client/src/components/mypages/MyReview.js
  client/src/pages/Register.js
  client/src/pages/ShoppingCart.js
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/reviewSlice.js
Labels: [FE]임세영, ✨ feature

#154 [Client] 최근 검색어, 인기 검색어 구현
  client/package-lock.json
  client/src/App.js
  client/src/apis/apis.js
  client/src/components/Footer.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/search.js
  client/src/pages/ShoppingCart.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/reduxstore/slices/articleSlice.js
Labels: [FE]김서연, ♻️ refactor

#155 ✨ feat : 인기검색어 10분마다 초기화
  server/src/main/java/gohome/dailydaily/DailydailyApplication.java
  server/src/main/java/gohome/dailydaily/domain/like/controller/LikeController.java
  server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
  server/src/main/java/gohome/dailydaily/domain/search/dto/SearchDto.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchRedisRepository.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchResRedisRepository.java
  server/src/main/java/gohome/dailydaily/domain/search/scheduler/SearchScheduler.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationEntryPoint.java
  server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
Labels: [BE]김경근, ✨ feature

#158 [Client] api refresh 오류 메세지에따른 응답 변환, 서브카테고리 수정한 파일 추가
  client/src/apis/apis.js
  client/src/components/mains/ImgSlider.js
  client/src/components/mains/Product.js
  client/src/components/mypages/MyReview.js
  client/src/imgs/noImg.gif
  client/src/pages/ShoppingCart.js
  client/src/pages/SubCategory.js
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/detail/Review.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/isLibrary.js
  client/src/reduxstore/slices/articleSlice.js
  client/src/reduxstore/slices/sub/isLibrarySlice.js
Labels: [FE]임세영, 🐞bug

#160 Revert "✨ feat : 인기검색어 10분마다 초기화"
  server/src/main/java/gohome/dailydaily/DailydailyApplication.java
  server/src/main/java/gohome/dailydaily/domain/like/controller/LikeController.java
  server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
  server/src/main/java/gohome/dailydaily/domain/search/dto/SearchDto.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchRedisRepository.java
  server/src/main/java/gohome/dailydaily/domain/search/repository/SearchResRedisRepository.java
  server/src/main/java/gohome/dailydaily/domain/search/scheduler/SearchScheduler.java
  server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
  server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationEntryPoint.java
  server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
Labels: 🐞bug

#161 [Client] 판매등록페이지 브랜드이름 셀렉트박스 변경
  client/src/components/mypages/MyReview.js
  client/src/pages/Register.js
  client/src/pages/detail/Review.js
Labels: [FE]임세영, ✨ feature

#162 ✨ feat : 상품 추가 시 유효성 검증 추가
  server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
  server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
  server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
  server/src/test/java/gohome/dailydaily/util/TestConstant.java
Labels: [BE]허준열, ✨ feature

#165 [Client]판매등록페이지 유효성검사 및 반응형 구현
  client/src/apis/apis.js
  client/src/components/effectivenessCheck.js
  client/src/components/mains/Calousel2.js
  client/src/components/mains/ImgSlider.js
  client/src/components/mypages/Pagination.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseList.js
  client/src/pages/Mypage.js
  client/src/pages/Register.js
  client/src/reduxstore/slices/myOrderSlice.js
Labels: [FE]노경민, ✨ feature

#167 [Client] 소분류 페이지 재수정
  client/src/App.js
  client/src/components/Header.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/pages/sub/LivingRoom.js
  client/src/reduxstore/slices/sub/LibrarySlice.js
Labels: [FE]김서연, ✨ feature
