Repository codestates-seb/seb40_main_013, pull requests merged in 2023-04, with the labels that each got.

#225 [FE] 메인페이지 카테고리별 신상품 타입스크립트 변환
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/apis/mainAPI.ts
  client/src/components/mains/BrandProductDetail.js
  client/src/components/mains/NewProductDetail.js
  client/src/components/mains/NewProducts.tsx
  client/src/pages/Main.tsx
  client/src/styles/NewProductsStyle.ts
Labels: [FE]노경민, ♻️ refactor

#226 [FE] Calousel refact
  client/package-lock.json
  client/package.json
  client/src/components/mains/Calousel.tsx
  client/src/components/mains/ImgSlider.ts
  client/src/pages/Main.tsx
  client/src/reduxstore/slices/articleSlice.js
  client/src/styles/Calousel.ts
  client/src/styles/styled.d.ts
Labels: [FE]노경민, ♻️ refactor

#228 [FE] 마이페이지 구매내역의 상세보기 isModal 변경
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/common/ScrollToTop.tsx
  client/src/components/mypages/PostReview.js
  client/src/components/mypages/PurchaseAll.js
  client/src/components/mypages/PurchaseDetail.tsx
  client/src/pages/Mypage.tsx
  client/src/pages/detail/ArticleDetail.js
  client/src/reduxstore/hooks.ts
  client/src/reduxstore/slices/myOrderSlice.js
  client/src/reduxstore/slices/myOrderSlice.tsx
  client/src/reduxstore/slices/userSlice.tsx
  client/src/reduxstore/store.ts
  client/src/styles/mypage/MypageStyle.tsx
  client/src/styles/mypage/PurchaseDetailStyle.ts
Labels: [FE]노경민, ♻️ refactor

#229 [FE] 구매내역페이지 타입변환
  client/src/components/Alert.js
  client/src/components/common/effectivenessCheck.tsx
  client/src/components/mypages/EditProfile.js
  client/src/components/mypages/PurchaseList.js
  client/src/components/mypages/PurchaseList.tsx
  client/src/pages/Register.js
  client/src/pages/Signup.js
  client/src/reduxstore/slices/myOrderSlice.tsx
  client/src/styles/mypage/PurchaseListStyle.ts
Labels: [FE]노경민, ♻️ refactor

#231 [FE] 로그인페이지,회원가입페이지 TypeScript 변환
  client/src/pages/Login.tsx
  client/src/pages/Signup.js
  client/src/pages/Signup.tsx
  client/src/reduxstore/slices/userSlice.tsx
  client/src/styles/Login.ts
  client/src/styles/Signup.ts
Labels: [FE]임세영, ♻️ refactor

#234 [FE] 헤더 TypeScript 변환
  client/.eslintrc.js
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Header.js
  client/src/components/Header.tsx
  client/src/components/common/effectivenessCheck.tsx
  client/src/components/mypages/PurchaseDetail.tsx
  client/src/pages/detail/ArticleDetail.js
  client/src/pages/sub/Bedroom.js
  client/src/pages/sub/Kitchen.js
  client/src/pages/sub/Library.js
  client/src/styles/HeaderStyle.ts
  client/src/styles/Signup.ts
Labels: [FE]김서연, ♻️ refactor

#235 [FE] 마이페이지 좋아요 관련 페이지들 ts로 변경, type.ts 생성
  client/src/components/common/Product.tsx
  client/src/components/mains/NewProducts.tsx
  client/src/components/mypages/Like.tsx
  client/src/components/mypages/PurchaseDetail.tsx
  client/src/pages/Main.tsx
  client/src/reduxstore/slices/likeSlice.js
  client/src/reduxstore/slices/likeSlice.tsx
  client/src/reduxstore/slices/myOrderSlice.tsx
  client/src/styles/mypage/LikeStyle.ts
  client/src/styles/mypage/MypageStyle.ts
  client/src/type.ts
Labels: [FE]노경민, ♻️ refactor
